import React from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'

export default function Home() {
  const { user } = useAuth()

  const features = [
    { icon: '📅', title: 'AI Study Planner', desc: 'Get personalized study plans generated by AI based on your goals and preferences.' },
    { icon: '📚', title: 'Content Library', desc: 'Access videos, articles, eBooks and quizzes across hundreds of topics.' },
    { icon: '🎯', title: 'Career Paths', desc: 'Explore curated career roadmaps with step-by-step guidance.' },
    { icon: '💬', title: 'AI Chatbot', desc: 'Get instant guidance on careers, study tips, and platform navigation.' },
    { icon: '👨‍🏫', title: 'Mentorship', desc: 'Connect with experienced mentors for personalized one-on-one sessions.' },
    { icon: '💼', title: 'Job Board', desc: 'Discover internships and jobs matched to your skills and interests.' },
  ]

  return (
    <div className="landing-page">
      <nav className="landing-nav">
        <div className="landing-logo">DreamCrafters</div>
        <div className="landing-nav-links">
          {user ? (
            <Link to="/dashboard" className="btn btn-primary">Dashboard</Link>
          ) : (
            <>
              <Link to="/login" className="btn btn-outline" style={{ borderColor: 'rgba(255,255,255,0.2)', color: 'white' }}>Login</Link>
              <Link to="/register" className="btn btn-primary">Get Started</Link>
            </>
          )}
        </div>
      </nav>

      <section className="hero">
        <div className="hero-content">
          <h1>
            Your Future Starts<br />
            with <span className="gradient-text">DreamCrafters</span>
          </h1>
          <p>
            An AI-powered learning platform that helps you plan your studies, 
            discover career paths, connect with mentors, and land your dream job.
          </p>
          <div className="hero-actions">
            {user ? (
              <Link to="/dashboard" className="btn btn-primary btn-lg">Go to Dashboard →</Link>
            ) : (
              <>
                <Link to="/register" className="btn btn-primary btn-lg">Create Free Account</Link>
                <Link to="/login" className="btn btn-secondary btn-lg" style={{ background: 'rgba(255,255,255,0.08)', border: '1px solid rgba(255,255,255,0.15)', color: 'white' }}>
                  Sign In
                </Link>
              </>
            )}
          </div>
        </div>
      </section>

      <section style={{ padding: '2rem 0 5rem' }}>
        <h2 style={{ textAlign: 'center', color: 'white', fontSize: '2rem', fontWeight: 800, marginBottom: '0.5rem' }}>
          Everything You Need
        </h2>
        <p style={{ textAlign: 'center', color: 'rgba(255,255,255,0.5)', marginBottom: '3rem', fontSize: '1.05rem' }}>
          One platform for learning, career growth, and mentorship
        </p>
        <div className="feature-grid">
          {features.map((f, i) => (
            <div className="feature-card" key={i}>
              <div className="icon">{f.icon}</div>
              <h3>{f.title}</h3>
              <p>{f.desc}</p>
            </div>
          ))}
        </div>
      </section>
    </div>
  )
}
